ScalefreeCOM/datavault4dbt

- README.md
- macros/tables/bigquery/rec_track_sat.sql
- macros/tables/control_snap_v1.sql
- macros/tables/exasol/control_snap_v1.sql
- macros/tables/exasol/rec_track_sat.sql
- macros/tables/snowflake/rec_track_sat.sql
is_weekly check is not supported in Exasol version Control Snapshot tables.
Global variables link in README.md was broken
Record tracking satellite macro converged in all DB versions - if no rsrc_static is defined in any models then the record source lookup wont be executed.
> Hotfix: Control snapshot in Exasol, Record tracking satellite (rsrc_static not defined) all versions

- macros/tables/bigquery/pit.sql
- macros/tables/exasol/pit.sql
- macros/tables/snowflake/pit.sql
Fixed some issues in PIT macro for snowflake:
- Quoting of pit_type value in column and hashing
- zero key of sat hkeys was not generated correctly
- the comparison of sdts with ldts changed from > to >= (otherwise a record with exactly the same ldts than the sdts would not be detected)
> Hotfix pit snowflake

- macros/supporting/hash.sql
- macros/supporting/hash_standardization.sql
When all inputs of a calculated hash value are NULL, the default unknown hash should be inserted. But that did not work, because the variable "all_null" was not properly forwarded to the concatenated_standardise macro. That has been fixed for all three adapters.
> Fixed the detection of NULL Inputs for Hash Calculation for all adapters

- macros/supporting/hash.sql
Before the ALL_NULL replacement was fixed in v1.0.5 the CASE WHEN took care of the replacement with the unknown key in the Exasol version of the hash macro. This is no longer necessary, therefore it was removed here.
> Removed Exasol hash macro CASE WHEN workaround

- macros/staging/bigquery/stage.sql
- macros/staging/exasol/stage.sql
- macros/staging/snowflake/stage.sql
- macros/staging/stage.sql
In the Stage macro the if statement with "is not none" only works if the sequence is not defined at all, so when it is defined and it is empty it will lead to compilation error due to printing "as edwSequence" without an input before.  Using the macro datavault4dbt.is_something() fixes this issue.
Also the if include_source_columns will lead to a compilation error if the parameter is passed as empty. This issue is fixed in the general dispatcher Stage macro.
> Fix bug in Stage Macro when sequence/include_source_columns is defined but it is empty

- macros/tables/bigquery/ma_sat_v0.sql
- macros/tables/exasol/ma_sat_v0.sql
- macros/tables/snowflake/ma_sat_v0.sql
This was missing : possibility to define hashdiff with input source column and alias with different name than the name of the source col. This feature is present already in sat_v0 macro, should also be present here.
> Added feature : different alias in ma_sat_v0 for Hashdiff

- macros/internal/metadata_processing/as_constant.sql
- macros/tables/bigquery/pit.sql
- macros/tables/bigquery/sat_v0.sql
- macros/tables/exasol/pit.sql
- macros/tables/exasol/sat_v0.sql
- macros/tables/snowflake/sat_v0.sql
The dash in the closing curly brackets(line 70 and 76 in Exasol) led to a lack of whitespace between the first and second iteration of the loop(when there is more than one source model) in the line 71... so the model when having two sources would run into an error because the line 75 or 77 would be glued with the line 71 that starts the LEFT JOIN again.  Removing these dashes of the closing curly brackets fixes the issue.
When using a different alias for hashdiff, the incremental run in the latest_entries_in_sat CTE fails because it tries to select the hashdiff with the name of the input column present in the source stage.
Replacing the variable src_hashdiff with ns.hdiff_alias in the latest_entries_in_sat CTE fixes this issue.
The user is now allowed to pass the column as an expression …
> Bugfixes - PIT, Sat_v0 and new feature in as_constant

- macros/staging/stage.sql
There was a problem with the previous fix in the Stage macro dispatching file, even when setting in the model the include_source_columns as false it was resetting here as true because of the logic inside the macro is_something.
> Fix of include_source_columns set of default value - Stage macro

- macros/tables/bigquery/pit.sql
- macros/tables/exasol/pit.sql
- macros/tables/snowflake/pit.sql
With this statement we now get only the distinct rows, so it now can support MA satellites since when joining with an SMA we would get duplicates because of the multiple rows related to the same hashkey
> Added DISTINCT statement to support MAS in PIT macro

- macros/supporting/hash_standardization.sql
The check for alias was not yet implemented in the Snowflake and default versions of the macro concattenated_standardise and multi_active_concattenated_standardise.
This PR includes this fixes and also replaces the single quote in the  CONCAT() of Snowflake that was generating a formatting problem in VS Code, with double quote.
> Hotfix v1.0.11 - concattenated_standardise Snowflake & Bigquery(default)

- macros/internal/helpers/is_checks.sql
- macros/staging/bigquery/stage.sql
- macros/staging/exasol/stage.sql
- macros/staging/snowflake/stage.sql
- macros/supporting/hash.sql
- macros/supporting/hash_default_values.sql
- macros/supporting/hash_standardization.sql
Setting the global variable "hash_datatype" to something else than "STRING" causes several issues: 
- The "LOWER()" function around the calculated hash value no longer works, because it requires a STRING input
- The default zero keys for hash values with "TO_BINARY()" do not work properly
- **hash_default_values** (Snowflake):
- Added the datatypes "VARCHAR", "CHAR" and "TEXT" as supported datatypes
- Fixed placement of quotes inside the Zero keys for binary values
- Added leading "!" for static zero keys to support usage of "as_constant" macro downstream
- **hash_default_values** (BigQuery):
- Removed filter for "STRING" datatype because datatype handling is done downstream
- Added leading "!" for static zero keys to support usage of "as_constant" macro downstream
- …
> Fixed "48 hash datatypes other than string cause an error"

- macros/tables/snowflake/control_snap_v0.sql
- **Control Snap v0** (Snowflake): "is_weekly" was set incorrectly, when DAYOFWEEK = 2. It is now set to DAYOFWEEK = 1 to set "is_weekly" to true for each Monday. If "is_weekly" still doesn't populate correctly for you, validate that the Snowflake Parameter [WEEK_START](https://docs.snowflake.com/en/sql-reference/parameters.html#week-start) is set to 0, by executing the following command in your Snowflake Session: 
`ALTER SESSION SET WEEK_START = 0;`
- @mjahammel Thanks for finding this issue!
> Fixed wrong "is_weekly" in snap_v0 for Snowflake

- packages.yml
- The maximum required version of dbt_utils is changed from 1.0.0.
> Raised dbt utils requirements to <2.0.0

- macros/tables/bigquery/pit.sql
- macros/tables/exasol/pit.sql
- macros/tables/snowflake/pit.sql
- **PIT** (All adapters): The zero key usage is now wrapped inside the "as_constant" macro, to make the zero key for BINARY/BYTES hash datatypes work.
> Fixed usage of zero keys in PIT macros for non-string datatypes

- macros/staging/snowflake/stage.sql
- macros/supporting/ghost_record_per_datatype.sql
- In the macro **snowflake__ghost_record_per_datatype** the length of the column is now taken into consideration if the column is of type VARCHAR or CHAR with specified char size(length). If the source column has length smaller than the length of the string unknown/error value datavault4dbt.error_value__STRING/datavault4dbt.unknown_value__STRING (both configured in dbt_project.yml) then it sets the ghost record with the alternative value for STRING, also configured in dbt_project.yml under the variables datavault4dbt.unknown_value_alt__STRING/datavault4dbt.error_value_alt__STRING
- In Snowflake **Stage** macro the col_size is now passed as an argument to datavault4dbt.ghost_record_per_datatype to account for the length for generating the unknown and error values for derived columns.
This …
> Fix ghost records derived datatypes

- macros/tables/bigquery/hub.sql
- macros/tables/bigquery/link.sql
- macros/tables/bigquery/nh_link.sql
- macros/tables/bigquery/rec_track_sat.sql
- macros/tables/exasol/hub.sql
- macros/tables/exasol/link.sql
- macros/tables/exasol/nh_link.sql
- macros/tables/exasol/rec_track_sat.sql
- macros/tables/snowflake/hub.sql
- macros/tables/snowflake/link.sql
- macros/tables/snowflake/nh_link.sql
- macros/tables/snowflake/rec_track_sat.sql
- In dbt Cloud, during an execution of "dbt build" or "dbt docs generate", the Job failed with the error message "This run exceeded your account's run memory limits."
- Occured for Multi Source Entities in incremental runs
- The background code checks for each source if it was included before, to disable the high-water-mark in such a case for this newly added source
- Here all the rows of each source are loaded into dbt and set as a variable
- With high volumes of data, this variable grows very big and therefore the account's memory is exceeded
- Instead of selecting all rows for each source, only a COUNT(*) is executed. This works fine, because later on the query results are only used to check if there are any rows, not to actually do something with the data. 
- This change is applied …
> Hotfix rsrs static query performance

- macros/supporting/ghost_record_per_datatype.sql
- **Stage (Derived Columns):** The datatype of derived columns, which is used for automatic ghost record generation, is now more robust against different input styles. Applying the two Jinja filters `| string | upper ` on the datatype variable now allows users to define their derived columns in various ways: 
```
derived_columns: 
test_column1:
value: '!teststring'
datatype: 'STRING'
test_column2:
value: '!teststring'
datatype: 'string'
test_column3:
value: '!teststring'
datatype: STRING
test_column4:
value: '!teststring'
datatype: string
```
Thanks to @lwehle for pointing this out!
> Added robustability to Derived Columns datatype definition

- macros/staging/bigquery/stage.sql
- macros/staging/exasol/stage.sql
- macros/staging/snowflake/stage.sql
- macros/supporting/ghost_record_per_datatype.sql
- macros/supporting/hash.sql
- macros/supporting/hash_method.sql
- macros/tables/bigquery/pit.sql
- macros/tables/exasol/pit.sql
- macros/tables/snowflake/pit.sql
Added the macro hash_method that dispatches the adapters and has a similar logic to the datavault4dbt.beginning_of_all_times and datavault4dbt.end_of_all_times macros.
Replaced the use of var('datavault4dbt.hash') with the macro call in other macros.
> Added macro for hash method

- macros/internal/helpers/stage_processing_macros.sql
- macros/internal/metadata_processing/multikey.sql
- macros/staging/bigquery/stage.sql
- macros/staging/exasol/stage.sql
- macros/staging/snowflake/stage.sql
- macros/staging/stage.sql
- Instead of prejoining to another dbt source, the parameter "ref_model" can be used instead of "src_name" & "src_table", to prejoin with other dbt models
- the parameters "this_column_name" & "ref_column_name" can now be set to a list of columns. Important: both need to have the same number of columns
- By default, these multiple join conditions are combined with an "AND". You can set another operator by adding the parameter "operator" to a prejoined column definition.
> Feature 1136 prejoin flexibility

- macros/supporting/hash_default_values.sql
The underlying Hash Macros are extended to also support "BINARY" datatype for MD5 hash algorithm.
> Added md5 binary support (Snowflake)

- macros/tables/bigquery/sat_v1.sql
- macros/tables/exasol/sat_v1.sql
- macros/tables/snowflake/sat_v1.sql
Fixed Issue that if add_is_current_flag is False, the comma behind {{ ledts_alias }} is falsly set.
> Changed minor Syntax-Error for Satellite v1 Macros

- macros/tables/bigquery/control_snap_v0.sql
- macros/tables/bigquery/control_snap_v1.sql
- macros/tables/control_snap_v0.sql
- macros/tables/control_snap_v1.sql
- macros/tables/exasol/control_snap_v0.sql
- macros/tables/exasol/control_snap_v1.sql
- macros/tables/snowflake/control_snap_v0.sql
- macros/tables/snowflake/control_snap_v1.sql
Added following columns to control snapshot v0 : is_end_of_month, is_quarterly and is_end_of_year
Extended logic in control snapshot v1 to allow for thes set of parameters 'end_of_month', 'quarterly' and 'end_of_year' in the definition of a log_logic dictionary.
> Extended log logic of snapshot control tables

- macros/supporting/hash_standardization.sql
The changed escaping of quote characters in the hash standardization macro does not work and breaks the hash function (in Snowflake).
> Removed "r" identifer in front of regex expression

- macros/staging/hash_columns.sql
- macros/supporting/hash.sql
- macros/supporting/hash_standardization.sql
When a new column or set of columns is added in the Satellite, the calculated hashdiff in the stage will be different even if the new column is NULL/all new columns are null. This results in many unnecessary new rows being added into the satellite. 
By using `append_new_columns `as value for the `on_schema_change `config variable in dbt (https://docs.getdbt.com/reference/resource-configs/vertica-configs#using-the-on_schema_change-config-parameter), you can use it in combination with the new OPTIONAL parameter `use_rtrim `introduced here in this PR, to avoid inserting a new row into the satellite when a new column is added to the payload in the hdiff and the new column holds a NULL value.
In an example model, the hashdiff for your satellite should be defined like this in the stage, for it …
> Added RTRIM Hashdiff Option for Snowflake

- macros/tables/bigquery/sat_v0.sql
- macros/tables/exasol/sat_v0.sql
- macros/tables/snowflake/sat_v0.sql
Split the logic in CTE `deduplicated_numbered_source` in the macro `sat_v0` into two different CTEs:
- First CTE deduplicate_qualify will apply the QUALIFY logic to the records present in the source_data deduplicating the source by comparing each hashdiff to the hashdiff of the previous record (in the stage), for each hashkey. 
- Second CTE has the same name as original CTE `deduplicated_numbered_source` and adds a ROW_NUMBER() based on hashkey when it is incremental
> Fixed: same hashdiff being inserted into satellite without in between deltas

- macros/tables/ref_table.sql
The attribute "snapshot_trigger_column" was not passed to the dispatch call. Therefore custom set variables would not affect the code right now. This is fixed!
Thanks to @DPolat-Scalefree for finding the problem!
> Passed "snapshot_trigger_column" to macro

- macros/tables/bigquery/control_snap_v0.sql
Since last update (datavault4dbt v.1.1.4) it was reported that this statement threw and error in BigQuery adapter:
```
CASE 
WHEN LAST_DAY(sdts, 'month') = DATE(sdts) THEN TRUE
ELSE FALSE
END as is_end_of_month,
```
The issue was resolved by replacing it with:
```
CASE 
WHEN LAST_DAY(DATE(sdts), MONTH) = DATE(sdts) THEN TRUE
ELSE FALSE
END as is_end_of_month,
```
> [BUGFIX][BigQuery] Fix Control Snapshot v0

- macros/supporting/ghost_record_per_datatype.sql
Add big query macro in macros/supporting/ghost_record_per_datatype.sql
Steps:
1. Copied the default__ macro to the bottom
2. Unquoted the `{{alias}}`
3. Changed `TO_DATE` to `PARSE_DATE` since `TO_DATE` is not supported in big query
4. Changed `date_format ` default value in big query macro to `'%Y-%m-%d'` because `'YYYY-MM-DD'` produced errors
5. Changed name to `bigquery__ghost_record_per_datatype`
> add big query macro in ghost_record_per_datatype

- dbt_project.yml
This pull request addresses an issue encountered with the datavault4dbt project on Redshift databases. Due to Redshift's lack of support for the BINARY(16) data type, using this data type causes syntax errors in compiled queries. To resolve this, I propose changing the data type of datavault4dbt.hash_datatype from BINARY(16) to VARCHAR(32).
This change is necessary to ensure that the datavault4dbt project is compatible with Redshift, enabling users to run datavault models without encountering syntax errors related to unsupported data types. More details can be found in the related issue: [Issue #171](https://github.com/ScalefreeCOM/datavault4dbt/issues/171).
The main change is in the dbt_project.yml configuration:
```
vars:
..
datavault4dbt.hash_datatype: 'VARCHAR(32)' # changed from …
```
> Change hash_datatype from BINARY(16) to VARCHAR(32) for Redshift Compatibility

- macros/supporting/hash_standardization.sql
Added CAST function to make the hash keys and hash diffs fields to use the defined datavault4dbt.hash_datatype, including the length, in Snowflake. 
Discussed in: [https://github.com/ScalefreeCOM/datavault4dbt/discussions/164](https://github.com/ScalefreeCOM/datavault4dbt/discussions/164)
> Added CAST() to fix hash_datatype length issue with Snowflake

- dbt_project.yml
- macros/staging/synapse/stage.sql
- macros/supporting/hash.sql
- macros/tables/synapse/pit.sql
This PR changes the global variable, as defined in the dbt_project.yml, for the `hash_datatype` back to String.
For the case, that no global variable is defined in the dbt_project.yml the default-values for synapse were changed to Binary(16) (staging/synapse/stage.sql, supporting/hash.sql, tables/synapse/pit.sql).
To inform Synapse users of the correct value for the global variable an addition to the [synapse specific notes](https://github.com/ScalefreeCOM/datavault4dbt/wiki/Synapse-Specific-Notes) should be made.
> Change global var hash datatype to string

- dbt_project.yml
This PR changes the value of `copy_rsrc_ldts_input_columns` back to false.
The hardcoded default in the staging macros is (unchanged) at false and the global variable default should reflect this behavior.
> change copy_rsrc_ldts_input_columns to false

- dbt_project.yml
- macros/staging/redshift/stage.sql
- macros/supporting/hash.sql
- macros/tables/redshift/pit.sql
Hi @thoffmann-sf,
the change from #172  did change the default global variable, which (if copied from the package) is used by all adapters.
This PR changes the hardcoded default values directly in the macros, which are used if no global variable is specified.
I could't find any other uses of `hash_datatype` for Redshift in the repo, but please add on if I missed something.
Also I have changed the default `hash_datatype` global variable in `dbt_project.yml` back to String.
Best Regards,
Theo
> change hardcoded default hash_datatype to varchar(32) for redshift macros

- macros/staging/snowflake/stage.sql
- The combination of Prejoins, and derived cols that rename columns, was not working properly, because not all columns were properly selected.
> Fixed combination of derived cols and prejoins in Snowflake

- macros/internal/helpers/stage_processing_macros.sql
- macros/staging/hash_columns.sql
- macros/supporting/ghost_record_per_datatype.sql
- Line 25 in hash_columns.sql would produce double commas, since there is also a comma outside the "if"-block, in line 36. This leads to a SQL Fail.
- Column names of Ghost Records in snowflake were not escaped
- Hash Input Columns, that are derived/prejoined columns, were not properly excluded, because the UPPER() mapping in stage_processing_macros.sql was not applied to both lists
> Removed double comma for Multi Active Hashkey calculation

- macros/supporting/current_timestamp.sql
fix dependency from dbt_utils to dbt because dbt_utils.current_timestamp was deprecated
> Update current_timestamp-macro, fix dependency

- macros/supporting/hash_standardization.sql
Remove unnecessary parameters from redshift and postgres concattenated_standardise macros
> Remove unnecessary parameters from concattenated standardise

- macros/supporting/hash.sql
Update hash.sql, remove hashdiff parameters from concattenated_standardise in redshift and postgres macros
> Update hash.sql, remove hashdiff parameters from concattenated_standardise

- macros/tables/pit.sql
- macros/tables/snowflake/pit.sql
The snowflake pit-macro now correctly handles the pit_type-string when it is prefixed by a !.
Update the [Wiki](https://github.com/ScalefreeCOM/datavault4dbt/wiki/PIT) after merging. (add remark, that pit_type should be prefixed by !)
> Add Snowflake pit_type static string support

- macros/staging/stage.sql
If no ldts is specified in the stage-macro-call the current timestamp will be used as value
> Update stage.sql, add default ldts value

- macros/tables/bigquery/hub.sql
- macros/tables/exasol/hub.sql
- macros/tables/postgres/hub.sql
- macros/tables/redshift/hub.sql
- macros/tables/synapse/hub.sql
fix hub key renaming if there are different namings for bk and hkey in the `source_model:` and the staging-model itself and there is only one source model
When only one source_model is specified inside the staging-macro but the source_model key-namings are differing from the definitions in the staging model the renaming would only happen when there are more than one source-model selected.
Related PR with more context: #239 
Manual testing via skeleton-project.
> fix hub key renaming if there are different namings for bk and hkey

- macros/staging/stage.sql
Reverts ScalefreeCOM/datavault4dbt#244
> Revert "Revert "Update stage.sql, add default ldts value""

- macros/staging/bigquery/stage.sql
- macros/staging/exasol/stage.sql
- macros/staging/postgres/stage.sql
- macros/staging/redshift/stage.sql
- macros/staging/snowflake/stage.sql
- macros/staging/synapse/stage.sql
Ghost records will only be created when the run is not incremental (and they are enabled)
> only create ghost records when it is not an incremental run

- macros/supporting/parse_iso8601.sql
- macros/supporting/parse_iso8601_date.sql
> delete unused macros

- macros/staging/redshift/stage.sql
Just a renaming issue for the stage macro from BigQuery to AWS Redshift
> Changing Google BigQuery to AWS Redshift

- macros/supporting/string_to_timestamp.sql
Update development branch
- [Add CAST to timestamp_default_dtype to postgres__string_to_timestamp](https://github.com/ScalefreeCOM/datavault4dbt/commit/acf923ec87d68f6472905eed8559da12f8193b2f)
> Cast postgres string to timestamp

- macros/supporting/string_to_timestamp.sql
Add CAST as timestamp_default_dtype to postgres__string_to_timestamp.
Allows users to define their desired timestamp datatype
> Add CAST as timestamp_default_dtype to postgres__string_to_timestamp

- macros/supporting/ghost_record_per_datatype.sql
beginning_of_all_times_date was used instead of beginning_of_all_times, therefore if the defaults were not changed the ghost record value of the unknown records had 00:00:00 instead of 00:00:01 as time.
This results in incorrect filtering of the ghost records by timestamp downstream
> fix redshift/postgres beginning_of_all_times unknown ghost record values

- macros/staging/redshift/stage.sql
Include a call of is_something(hashed_columns) in the redshift stage to before the hashed_columns variable is accessed.
In a stage with no hashed_columns there is a compilation error without this check
> fix redshift stage compilation error when no hashed columns are provided

- macros/staging/fabric/stage.sql
- macros/tables/fabric/rec_track_sat.sql
Stage and rec_track_sat of fabric did not use the new string_default_dtype-macro
> update fabric stage and rec_track_sat to use sring_default_dtype()

- macros/supporting/ghost_record_per_datatype.sql
Add the datatypes Array and Variant to Snowflake ghost records
> Add the datatypes Array and Variant to Snowflake ghost records

- macros/supporting/ghost_record_per_datatype.sql
improve handling of the various timestamp formats in snowflake ghost records
also improve numeric data type handling for ghost records
> improve handling of the various timestamp formats in snowflake ghost records

- macros/tables/databricks/pit.sql
- macros/tables/postgres/pit.sql
- macros/tables/redshift/pit.sql
timestamp_sub is not supported in databricks and postgres, therefore it needed to be replaced with arithmetic syntax.
dateadd in conjunction with referencing a column did cause an error in redshift, therefore it was also replaced with arithmetic syntax
> FIX:databricks/postgres/redshift: replace unsupported timestamp_sub- and dateadd-functions

- macros/supporting/ghost_record_per_datatype.sql
add `fix:synapse/exasol: ghostrecords for timestamps didnt use alias-variable` to eff-sat-branch, otherwise the pipeline fails because the fix is not present
> add fix:synapse/exasol: ghostrecords for timestamps didnt use alias-variable to eff-sat-branch

- macros/supporting/ghost_record_per_datatype.sql
fix: synapse and exasol: ghostrecords for timestamps didnt use alias-variable
> fix:synapse/exasol: ghostrecords for timestamps didnt use alias-variable

- macros/tables/fabric/sat_v0.sql
Sat v0 Macro for Fabric had a "|lower" after the hashky inside the "PARTITION BY" clauses. This causes issues with column names, if they are upper case. 
> Fixed PARTION BY Clause in Sat v0 for Fabric

- macros/tables/redshift/eff_sat_v0.sql
- macros/tables/redshift/hub.sql
- macros/tables/redshift/link.sql
- macros/tables/redshift/ma_sat_v0.sql
- macros/tables/redshift/nh_link.sql
- macros/tables/redshift/ref_sat_v0.sql
- macros/tables/redshift/sat_v0.sql
All macros that need to get the latest existing records now use QUALIFY instead of an additional CTE with ROW_NUMBER() and WHERE. This massively boosts performance.
Fixes #298 
> Redshift: Use QUALIFY statement instead of prep-CTEs to enhance performance

- macros/staging/stage_processing_macros.sql
add adapter dispatch to process_columns_to_select so it can be overridden by users
Fixes #307 
https://github.com/ScalefreeCOM/datavault4dbt-ci-cd/actions/runs/12913086057/job/36009629640
> add adapter dispatch to process_columns_to_select

- macros/supporting/hash_default_values.sql
- macros/tables/snowflake/rec_track_sat.sql
add md5_binary to the supported algorithms for the snowflake hash_default_values
Also include a fix for the record tracking satellite because the snowflake CONCAT() function does not allow binary and string in the same statement
Fixes #306
> add md5-binary support for snowflake

- macros/staging/stage_processing_macros.sql
To fix upper- & lowercase of column names in stages for Fabric only. 
> Fabric specific stage processing macro

- macros/staging/fabric/stage.sql
- macros/tables/fabric/eff_sat_v0.sql
- macros/tables/fabric/hub.sql
- macros/tables/fabric/link.sql
- macros/tables/fabric/ma_sat_v0.sql
- macros/tables/fabric/ma_sat_v1.sql
- macros/tables/fabric/nh_link.sql
- macros/tables/fabric/nh_sat.sql
- macros/tables/fabric/pit.sql
- macros/tables/fabric/rec_track_sat.sql
- macros/tables/fabric/ref_hub.sql
- macros/tables/fabric/ref_sat_v0.sql
- macros/tables/fabric/ref_sat_v1.sql
- macros/tables/fabric/ref_table.sql
- macros/tables/fabric/sat_v0.sql
- macros/tables/fabric/sat_v1.sql
`prepend_generated_by()` moved after `WITH` to allow Data Preview for Microsoft Fabric for all front-end macros.
> [Fabric] Move prepend generated by after first with to allow data preview

- macros/internal/helpers/is_checks.sql
- macros/internal/metadata_processing/yaml_metadata_parser.sql
If a top-level macro parameter was set to `false` it was falsely treated the same way as if no value was set.
To accommodate this the check in the `yaml_metadata_parser` was modified.
Fixes #321 
> fix yaml_metadata_parser to not treat false values like none values

- macros/supporting/hash_default_values.sql
The md5_binary hash default value contained 40 instead of 32 characters
> fix snowflake md5 binary default values

- macros/internal/metadata_processing/escape_column_names.sql
- macros/staging/stage_processing_macros.sql
- macros/tables/databricks/ma_sat_v1.sql
- macros/tables/databricks/ref_sat_v1.sql
- macros/tables/databricks/sat_v1.sql
- macros/tables/fabric/sat_v1.sql
- Adds Databricks support for upper & lower case column names via the `datavault4dbt.set_casing` variable. 
Replicates the existing implementation that was recently implemented for Fabric providers
- Includes `is_current` set_casing support for the bug mentioned below for Databricks provider
- Includes `is_current` set_casing support for sat_v1 object for the Fabric provider to match case settings for existing Fabric ma_sat_v1 & ref_sat_v1 objects.
- The existing Fabric implemented was replicated 
- Each of the Datavault specific table types was tested and verified that they produced upper or lower case field names depending on the setting
**Test Configuration**:
* datavault4dbt-Version: 1.92
* dbt-Version: core, version number_1.9.2
* …
> Adding Upper/Lower case field naming support for Databricks

- macros/internal/metadata_processing/escape_column_names.sql
- macros/staging/stage_processing_macros.sql
- macros/tables/databricks/hub.sql
- macros/tables/databricks/link.sql
- macros/tables/databricks/ma_sat_v0.sql
- macros/tables/databricks/ma_sat_v1.sql
- macros/tables/databricks/nh_link.sql
- macros/tables/databricks/nh_sat.sql
- macros/tables/databricks/pit.sql
- macros/tables/databricks/rec_track_sat.sql
- macros/tables/databricks/ref_hub.sql
- macros/tables/databricks/ref_sat_v0.sql
- macros/tables/databricks/ref_sat_v1.sql
- macros/tables/databricks/ref_table.sql
- macros/tables/databricks/sat_v0.sql
- macros/tables/databricks/sat_v1.sql
- macros/tables/fabric/sat_v1.sql
- Adds Databricks support for upper & lower case column names via the `datavault4dbt.set_casing` variable. 
Replicates the existing implementation that was recently implemented for Fabric providers
- Includes `is_current` set_casing support for the bug mentioned in #315 
- Includes `is_current` set_casing support for sat_v1 object for the Fabric provider to match case settings for existing Fabric ma_sat_v1 & ref_sat_v1 objects.
Fixes #315
Thanks to @diveyseek for the groundwork!
> Add databricks column case sensitivity setting via set_casing variable

- macros/supporting/hash_default_values.sql
- macros/supporting/hash_standardization.sql
SHA2 is the SQL function in Redshift, therefore specific hash-default_value.sql is required and added in this PR
Fixes #333
> added redshift specific hash_default_values to support SHA256

- macros/supporting/hash_default_values.sql
- macros/supporting/hash_standardization.sql
add hash_default_values for databricks to properly support the hash algorithms
Fixes #342
> fix: add hash_default_values for databricks

- macros/supporting/hash.sql
- macros/supporting/hash_standardization.sql
Due to the `concat()` function allowing a maximum of 254 arguments it was only possible to specify 127 columns for a hashdiff.
By switching to `concat_ws()` the maximum number of columns for a hashdiff is now 253.
Thanks to @dga-isr for pointing this out and proposing the fix using `concat_ws()`!
Additionally the hashdiff-standardization now also includes a `CAST()` to Varchar to allow varbinary payloads.
Fixes #352 
> FIX: 352 bug stage macro fails for ms fabric when source table has more than 127 columns

- macros/staging/bigquery/stage.sql
- macros/staging/databricks/stage.sql
- macros/staging/exasol/stage.sql
- macros/staging/fabric/stage.sql
- macros/staging/oracle/stage.sql
- macros/staging/postgres/stage.sql
- macros/staging/redshift/stage.sql
- macros/staging/snowflake/stage.sql
- macros/staging/stage_processing_macros.sql
- macros/staging/synapse/stage.sql
This Pull Request handles the new feature which is described here: https://github.com/ScalefreeCOM/datavault4dbt/issues/348
@tkiehn @tkirschke Would be happy if you might take a look into it and tell me your opinion :)
Adds a new Parameter called "join_type" for Prejoining. It allows user to define in specific usecases a Join-Type different than LEFT Join. However, if the parameter is not set, left join is taken as default. Due to that there shouldn't be any issues with backward compatibility.
Examples for now supported Join Types: INNER, LEFT, RIGHT, CROSS, OUTER, FULL
Tested it on Databricks Environment and checked the compiled Code of existing Staging model in the following usecases:
**Test Configuration**:
* datavault4dbt-Version: 1.9.10
* dbt-Version: core, 1.10.9
* …
> add 'join_type' parameter in staging
