- macros/staging/derived_column_datatypes.sql
- macros/staging/exasol/stage.sql
- macros/supporting/ghost_record_per_datatype.sql
- macros/supporting/hash.sql
- macros/supporting/hash_standardization.sql
- macros/tables/exasol/control_snap_v0.sql
- macros/tables/exasol/control_snap_v1.sql
- **Resolved**: is_weekly snapshot check now working in Control Snapshots in Exasol and corrected caption column
- **Fixed** ghost record creation for Exasol Stage (they were always being created with maximum length for the string/VARCHAR datatype because of an update in dbt-exasol)
- **New** optional argument added to **ghost_record_per_datatype** macro : **col_size** (to resolve ghost record column length)
-  **New** key to output result dictionary in **derived_column_datatypes**  macro : **col_size**
> Hotfix v1.0.3

- macros/tables/bigquery/pit.sql
- macros/tables/exasol/pit.sql
- macros/tables/snowflake/pit.sql
Fixed an issue in joins when satellites without a load end date were used to build a PIT table
> Fixed PIT joins

- macros/tables/bigquery/sat_v1.sql
- macros/tables/exasol/sat_v1.sql
- macros/tables/sat_v1.sql
- macros/tables/snowflake/sat_v1.sql
Default of the parameter is true.
If user sets it to false it wont include the payload (source) columns from sat_v0
> New Optional Parameter include_payload added to sat_v1

- macros/tables/exasol/hub.sql
- macros/tables/exasol/link.sql
- macros/tables/exasol/nh_link.sql
- macros/tables/exasol/rec_track_sat.sql
Applied the disable_hwm and Multi Source, same source multiple times to the table macros for Exasol Adapter:
- nh_link - made the dedup optional as well
- link
- hub
- rec_track_sat
> V1.1 exasol changes

- macros/staging/bigquery/stage.sql
- macros/staging/exasol/stage.sql
- macros/staging/snowflake/stage.sql
- macros/tables/exasol/nh_link.sql
"include_source_columns=false" caused problems on Multi Active Stages, because the Multi Active Keys were not included in the column selection. 
Fixed this now on all Database Adapters.
> Multi active stage include src cols fix

- macros/tables/sqlserver/hub.sql
- macros/tables/sqlserver/link.sql
- macros/tables/sqlserver/ma_sat_v0.sql
- macros/tables/sqlserver/nh_link.sql
- macros/tables/sqlserver/nh_sat.sql
- macros/tables/sqlserver/pit.sql
- macros/tables/sqlserver/rec_track_sat.sql
- macros/tables/sqlserver/ref_hub.sql
- macros/tables/sqlserver/ref_sat_v0.sql
- macros/tables/sqlserver/ref_table.sql
- macros/tables/sqlserver/sat_v0.sql
Modified Code for SQL Server specific performance boosts
> Sqlserver review dp

- macros/tables/bigquery/ref_sat_v1.sql
- macros/tables/bigquery/sat_v1.sql
- macros/tables/exasol/ref_sat_v1.sql
- macros/tables/ref_sat_v1.sql
- macros/tables/sat_v1.sql
- macros/tables/snowflake/ref_sat_v1.sql
- macros/tables/snowflake/sat_v1.sql
Thanks to @jabibo for noticing a faulty way of setting the ledts_alias!
> Changed the way of ledts_alias setting

- macros/tables/bigquery/control_snap_v1.sql
- macros/tables/exasol/control_snap_v1.sql
- macros/tables/snowflake/control_snap_v1.sql
Added a counter to check if it needs to use the 'OR' in the if statements for the log_logic keys.
Added fix for all adapters.
> Added fix for ctrl snapshot v1 log_logic

- macros/tables/bigquery/rec_track_sat.sql
- macros/tables/exasol/rec_track_sat.sql
Run correct query to get the right source count for existing sources.
> Applied fix in rec_track_sat macro for Exasol and BigQuery

- README.md
Added synapse support to readme file
> Added Synapse Support to Readme

- macros/supporting/hash_standardization.sql
- macros/tables/postgres/control_snap_v0.sql
add parameters to postgres macros so they have the needed amount of parameters
> Add parameters to postgres macros

- macros/tables/bigquery/ref_sat_v0.sql
- macros/tables/exasol/ref_sat_v0.sql
- macros/tables/postgres/ref_sat_v0.sql
- macros/tables/redshift/ref_sat_v0.sql
- macros/tables/snowflake/ref_sat_v0.sql
Add disable_hwm conditions to the ref_sat_v0 macros
> Add disable_hwm conditions to the ref_sat_v0 macros

- macros/supporting/hash.sql
- macros/supporting/hash_standardization.sql
- macros/tables/exasol/hub.sql
- macros/tables/exasol/link.sql
- macros/tables/exasol/rec_track_sat.sql
- macros/tables/postgres/sat_v0.sql
- macros/tables/redshift/sat_v0.sql
Merge fixes for missing macro parameters into hotfix branch
> Merge parameter fixes 

- .github/workflows/close_inactive_issues.yml
Add Github Action to label issues as stale and close them after a certain time.
> Add Github Action to label issues

- macros/staging/bigquery/stage.sql
- Hotfix for the multi active hash diff calculation
> Hotfix multi active sat stage bigquery

- .github/workflows/checking_labels.yml
- .github/workflows/trigger_remote_workflow.yml
Just added two workflow files, so I can test the implementation of the testing workflow in my branch.
> Added workflow files for testing on branch.

- macros/tables/snowflake/rec_track_sat.sql
Merge of the Rec Track Sat fix for Snowflake by Tim K.
> Fixed to run a COUNT instead of full scan

- macros/supporting/ghost_record_per_datatype.sql
- macros/tables/bigquery/ref_hub.sql
- macros/tables/exasol/ref_hub.sql
- macros/tables/postgres/ref_hub.sql
- macros/tables/redshift/ref_hub.sql
- macros/tables/snowflake/ref_hub.sql
- macros/tables/synapse/ref_hub.sql
1. [implement ref key not null check in ref_hub macros](https://github.com/ScalefreeCOM/datavault4dbt/commit/806c379e0bd8a59c7b76b745e13e6faf8a829abd)
2. [add text to snowflake ghost records](https://github.com/ScalefreeCOM/datavault4dbt/commit/cf7a15c712614cc8c3d5c49c6ef9a5d0fd47010e)
> Implement ref key no null check and add text to snowflake ghost records

- macros/staging/stage.sql
Reverts ScalefreeCOM/datavault4dbt#243
> Revert "Update stage.sql, add default ldts value"

- .github/workflows/checking_labels.yml
- .github/workflows/trigger_remote_workflow.yml
No changes, just added explanation in code for workflows.
> Added code explanation for workflow files.

- macros/supporting/ghost_record_per_datatype.sql
Fix the creation of ghost records for binary datatype on databricks
Fixes #299 
Created models like in the linked issue and successfully ran them
> fix databricks ghost records for binary datatype

- macros/tables/bigquery/control_snap_v0.sql
- macros/tables/databricks/control_snap_v0.sql
- macros/tables/exasol/control_snap_v0.sql
- macros/tables/fabric/control_snap_v0.sql
- macros/tables/oracle/control_snap_v0.sql
- macros/tables/postgres/control_snap_v0.sql
- macros/tables/redshift/control_snap_v0.sql
- macros/tables/snowflake/control_snap_v0.sql
- macros/tables/synapse/control_snap_v0.sql
Implement the `end_date` parameter for the control_snap_v0-tables.
This allows setting the last date for the generated tables
> 179 snapshot control v0 implement end date

- macros/tables/snowflake/sat_v0.sql
Moves max(ldts) to separate run_query()
Fixes #335
> Snowflake-Sat_v0: Performance improvement: Move max(ldts) into run_query() (#336)

- dbt_project.yml
- macros/supporting/timestamp_default_dtype.sql
add missing default values for databricks
Fixes #344
> Fix: add missing default values for databricks

- macros/supporting/ghost_record_per_datatype.sql
fix snowflake variant ghost records by calling object_construct()
> fix snowflake variant ghost records

- README.md
Update link to premium package
> Update link to premium package
